import json
from logging import config
from pathlib import Path
from typing import Optional

from .constants import OlivePassNames, OlivePropertyNames, PhaseTypeEnum
from .generator_common import create_model_parameter
from .model_info import ModelList
from .model_parameter import Section, ModelParameter, OptimizationPath
from .utils import isLLM_by_id, open_ex
from .parameters import Parameter

def generate_quantization_config(configFile: Path, parameter: ModelParameter) -> Optional[Section]:
    """
    Generates a quantization configuration section for the given file.
    """
    with open_ex(configFile, "r") as f:
        content = json.load(f)
    parameters = []
    for k, v in content[OlivePropertyNames.Passes].items():
        if v[OlivePropertyNames.Type].lower() == OlivePassNames.ModelBuilder:
            path = f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.Precision}"
            parameters.append(
                Parameter(
                    autoGenerated=True,
                    template=Parameter(
                        template="ModelBuilderPrecision",
                        path=path,
                    ),
                )
            )
            parameter.optimizationPaths.append(
                OptimizationPath(path=path))

    if parameters:
        return Section(
            autoGenerated=True,
            name="Optimization",
            phase=PhaseTypeEnum.Quantization,
            parameters=parameters,
        )
    return None


def generator_dml(id: str, recipe, folder: Path, modelList: ModelList):
    aitk = recipe.get("aitk", {})
    auto = aitk.get("auto", True)
    isLLM = isLLM_by_id(id)
    if not auto or not isLLM:
        return
    name = "Convert to DirectML"

    file = recipe.get("file")
    configFile = folder / file

    parameter = create_model_parameter(aitk, name, configFile)
    parameter.isLLM = isLLM

    quantize = generate_quantization_config(configFile, parameter)
    if quantize:
        parameter.sections.append(quantize)

    parameter.writeIfChanged()
    print(f"\tGenerated DML configuration for {file}")
