import json
from pathlib import Path
from typing import Optional

from .constants import OlivePassNames, OlivePropertyNames, PhaseTypeEnum
from .model_info import ModelList
from .model_parameter import ModelParameter, RuntimeOverwrite, Section
from .parameters import Parameter
from .utils import isLLM_by_id, open_ex


def generate_quantization_config(folder: Path, file: str, modelList: ModelList) -> Optional[Section]:
    """
    Generates a quantization configuration section for the given file.
    """
    with open_ex(folder / file, "r") as f:
        content = json.load(f)
    parameters = []
    data_configs = content.get(OlivePropertyNames.DataConfigs, [])
    for k, v in content[OlivePropertyNames.Passes].items():
        if v[OlivePropertyNames.Type].lower() == OlivePassNames.OnnxStaticQuantization:
            activation_type = v.get(OlivePropertyNames.ActivationType)
            if activation_type:
                parameters.append(
                    Parameter(
                        template=Parameter(
                            autoGenerated=True,
                            template="ActivationType",
                            path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.ActivationType}",
                        )
                    )
                )
            precision = v.get(OlivePropertyNames.Precision)
            if precision:
                parameters.append(
                    Parameter(
                        template=Parameter(
                            autoGenerated=True,
                            template="WeightType",
                            path=f"{OlivePropertyNames.Passes}.{k}.{OlivePropertyNames.Precision}",
                        )
                    )
                )
            data_config = v.get(OlivePropertyNames.DataConfig)
            if data_config:
                for i in range(len(data_configs)):
                    if data_configs[i].get(OlivePropertyNames.Name) == data_config:
                        load_dataset_config = data_configs[i].get(OlivePropertyNames.LoadDatasetConfig)
                        data_name = load_dataset_config.get(OlivePropertyNames.DataName)
                        parameters.append(
                            Parameter(
                                template=Parameter(
                                    autoGenerated=True,
                                    template="QuantizationDataset",
                                    path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.LoadDatasetConfig}.{OlivePropertyNames.DataName}",
                                    values=[data_name],
                                )
                            )
                        )

                        subset = load_dataset_config.get(OlivePropertyNames.Subset)
                        if subset:
                            subsets = modelList.DatasetSubset.get(data_name)
                            if not subsets:
                                subsets = [subset]
                            parameters.append(
                                Parameter(
                                    template=Parameter(
                                        autoGenerated=True,
                                        template="QuantizationDatasetSubset",
                                        path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.LoadDatasetConfig}.{OlivePropertyNames.Subset}",
                                        values=subsets,
                                    )
                                )
                            )

                        split = load_dataset_config.get(OlivePropertyNames.Split)
                        if split:
                            # use template default or DatasetSplit
                            splits = modelList.DatasetSplit.get(data_name)
                            parameters.append(
                                Parameter(
                                    template=Parameter(
                                        autoGenerated=True,
                                        template="QuantizationDatasetSplit",
                                        path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.LoadDatasetConfig}.{OlivePropertyNames.Split}",
                                        values=splits,
                                    )
                                )
                            )

                        pre_process_data_config = data_configs[i].get(OlivePropertyNames.PreProcessDataConfig)
                        max_samples = pre_process_data_config.get(OlivePropertyNames.MaxSamples)
                        if max_samples:
                            parameters.append(
                                Parameter(
                                    template=Parameter(
                                        autoGenerated=True,
                                        template="QuantizationDatasetSize",
                                        path=f"{OlivePropertyNames.DataConfigs}[{i}].{OlivePropertyNames.PreProcessDataConfig}.{OlivePropertyNames.MaxSamples}",
                                    )
                                )
                            )
                        break

    if parameters:
        return Section(
            autoGenerated=True,
            name="Quantize",
            phase=PhaseTypeEnum.Quantization,
            parameters=parameters,
        )
    return None


def generator_amd(id: str, recipe, folder: Path, modelList: ModelList):
    aitk = recipe.get("aitk", {})
    auto = aitk.get("auto", True)
    isLLM = isLLM_by_id(id)
    if not auto or not isLLM:
        return
    amd_runtime_values: list[str] = recipe.get("devices", [recipe.get("device")])
    file = recipe.get("file")

    name = f"Convert to AMD {"/".join([runtime.upper() for runtime in amd_runtime_values])}"
    addCpu = False
    oliveFile = aitk.get("oliveFile")

    sections = []
    quantize = generate_quantization_config(folder, file, modelList)
    if quantize:
        sections.append(quantize)

    requirements = aitk.get("requirements")
    runtimeOverwrite = None
    if requirements:
        runtimeOverwrite = RuntimeOverwrite(autoGenerated=True, executeRequirement=requirements)
    aitkRuntimeOverwrite = aitk.get("runtimeOverwrite")
    if aitkRuntimeOverwrite:
        if runtimeOverwrite is None:
            runtimeOverwrite = RuntimeOverwrite(autoGenerated=True)
        executeEp = aitkRuntimeOverwrite.get("executeEp")
        runtimeOverwrite.executeEp = executeEp

    requirements_patches = aitk.get("requirementsPatches")
    evalRuntime = aitk.get("evalRuntime")

    parameter = ModelParameter(
        name=name,
        isLLM=isLLM,
        addCpu=addCpu,
        oliveFile=oliveFile,
        sections=sections,
        runtimeOverwrite=runtimeOverwrite,
        executeRuntimeFeatures=requirements_patches,
        evalRuntime=evalRuntime,
    )
    parameter._file = str(folder / (file + ".config"))
    parameter.writeIfChanged()
    print(f"\tGenerated AMD configuration for {file}")
