"""Export CUDA models for Qwen VL and assemble models/ directory.

Steps:
1. Run Olive to export text model with CUDA EP (int4 + fp16) via ModelBuilder
2. Run Olive to export embedding model with fp16 + int4 quantization
3. Run Olive to export vision model with fp16 + int4 quantization
4. Patch genai_config.json with embedding/vision sections + CUDA provider_options

Usage (from the cuda/ directory):
    python export.py
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path


def run_olive(config_path: Path, olive_dir: Path) -> None:
    """Run an Olive config and exit on failure."""
    result = subprocess.run(
        [sys.executable, "-m", "olive", "run", "--config", str(config_path)],
        cwd=str(olive_dir),
    )
    if result.returncode != 0:
        print(f"ERROR: Olive run failed for {config_path.name}")
        sys.exit(1)


def flatten_subdir(models_dir: Path, name: str) -> None:
    """If Olive output is in a subdirectory, flatten it up one level."""
    subdir = models_dir / f"{name}.onnx"
    if subdir.is_dir():
        for f in subdir.iterdir():
            dest = models_dir / f.name
            if dest.exists():
                if dest.is_dir():
                    shutil.rmtree(dest)
                else:
                    dest.unlink()
            shutil.move(str(f), str(dest))
        subdir.rmdir()
        print(f"  Moved {name} files from {subdir} to {models_dir}")


def main():
    cuda_dir = Path.cwd()
    cpu_models = cuda_dir.parent / "cpu_and_mobile" / "models"
    models = cuda_dir / "models"

    if not cpu_models.exists():
        print(f"ERROR: {cpu_models} not found. Export CPU models first.")
        sys.exit(1)

    # Step 1: Export text model with CUDA EP (int4 + fp16 via ModelBuilder)
    print("=" * 60)
    print("Step 1: Exporting text model (int4 + fp16, CUDA EP)...")
    print("=" * 60)
    run_olive(cuda_dir / "text.json", cuda_dir)
    flatten_subdir(models, "text")

    # Step 2: Export embedding model with fp16 + int4
    print("\n" + "=" * 60)
    print("Step 2: Exporting embedding model (fp16 + int4)...")
    print("=" * 60)
    run_olive(cuda_dir / "embedding.json", cuda_dir)
    flatten_subdir(models, "embedding")

    # Step 3: Export vision model with fp16 + int4
    print("\n" + "=" * 60)
    print("Step 3: Exporting vision model (fp16 + int4)...")
    print("=" * 60)
    run_olive(cuda_dir / "vision.json", cuda_dir)
    flatten_subdir(models, "vision")

    # Step 4: Patch genai_config.json
    print("\n" + "=" * 60)
    print("Step 4: Patching genai_config.json with CUDA provider options...")
    print("=" * 60)

    # Load the CPU genai_config (contains complete embedding/vision sections)
    cpu_config_path = cpu_models / "genai_config.json"
    with open(cpu_config_path) as f:
        cpu_config = json.load(f)

    # Load the CUDA genai_config (generated by ModelBuilder, only has decoder + search)
    cuda_config_path = models / "genai_config.json"
    with open(cuda_config_path) as f:
        cuda_config = json.load(f)

    cuda_provider_options = [{"cuda": {}}]

    # Add CUDA provider_options to decoder session
    if "decoder" in cuda_config.get("model", {}):
        cuda_config["model"]["decoder"].setdefault("session_options", {})
        cuda_config["model"]["decoder"]["session_options"]["provider_options"] = cuda_provider_options

    # Copy embedding section from CPU config and add CUDA provider_options
    if "embedding" in cpu_config.get("model", {}):
        cuda_config["model"]["embedding"] = cpu_config["model"]["embedding"]
        cuda_config["model"]["embedding"].setdefault("session_options", {})
        cuda_config["model"]["embedding"]["session_options"]["provider_options"] = cuda_provider_options

    # Copy vision section from CPU config and add CUDA provider_options
    if "vision" in cpu_config.get("model", {}):
        cuda_config["model"]["vision"] = cpu_config["model"]["vision"]
        cuda_config["model"]["vision"].setdefault("session_options", {})
        cuda_config["model"]["vision"]["session_options"]["provider_options"] = cuda_provider_options

    # Copy VL-specific token IDs from CPU config
    for key in ["image_token_id", "video_token_id", "vision_start_token_id"]:
        if key in cpu_config.get("model", {}):
            cuda_config["model"][key] = cpu_config["model"][key]

    with open(cuda_config_path, "w") as f:
        json.dump(cuda_config, f, indent=2)
    print(f"  Updated {cuda_config_path}")

    # Step 5: Copy processor_config.json if needed (referenced by vision section)
    for extra in ["processor_config.json"]:
        src = cpu_models / extra
        dst = models / extra
        if src.exists() and not dst.exists():
            shutil.copy2(str(src), str(dst))
            print(f"  Copied {extra}")

    # Summary
    print("\n" + "=" * 60)
    print("CUDA model export complete! (int4 + fp16)")
    print("=" * 60)
    print(f"  Output: {models}")
    print(f"  Files:")
    for f in sorted(models.iterdir()):
        size = f.stat().st_size
        if size > 1e6:
            print(f"    {f.name:40s} {size / 1e6:>10.1f} MB")
        else:
            print(f"    {f.name:40s} {size / 1e3:>10.1f} KB")

    # Clean up olive cache
    cache_dir = cuda_dir / ".olive-cache"
    if cache_dir.exists():
        shutil.rmtree(cache_dir)
        print(f"\n  Cleaned up {cache_dir}")


if __name__ == "__main__":
    main()
