name: "Workflow to verify AITK recipes"

on:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r .aitk/scripts/requirements.txt
          pip install check-jsonschema
      - name: Validate config schema
        run: |
          find . -name "*.json.config" ! -name "_copy.json.config" \
            | xargs check-jsonschema --schemafile .aitk/configs/config_schema.json
      - name: Run script
        run: python .aitk/scripts/sanitize.py
