name: Olive Recipes CI

on:
  schedule:
    - cron: '0 15 * * 5'
  # Temporary: Remove these 3 lines after testing is complete
  push:
    branches:
      - recipes-ci
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        default: false
      test_scope:
        type: choice
        options:
          - all
          - linux-cpu-only
          - linux-gpu-only
          - windows-cpu-only
        default: all

env:
  PYTHON_VERSION: "3.10"

jobs:
  linux-cpu:
    name: Linux CPU - ${{ matrix.name }}
    if: |
      github.event.inputs.test_scope == 'all' || 
      github.event.inputs.test_scope == 'linux-cpu-only' || 
      github.event.inputs.test_scope == ''
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "PTQ"
            path: "intel-bert-base-uncased-mrpc/oci/cpu"
            config: "ptq.json"
          - name: "INC Smooth Quant"
            path: "intel-bert-base-uncased-mrpc/oci/cpu"
            config: "inc_smooth_quant.json"
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Olive
        run: pip install git+https://github.com/microsoft/Olive.git@main
      
      - name: Install requirements
        working-directory: ${{ matrix.path }}
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run and verify
        working-directory: ${{ matrix.path }}
        env:
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
        run: |
          python -m olive run --config ${{ matrix.config }}
          python -c "
          from olive.workflows.run import WorkflowOutput
          import sys
          try:
              output = WorkflowOutput.from_json('olive-output/output.json')
              if output.has_output_model():
                  model = output.get_best_candidate()
                  print(f'SUCCESS: Model at {model.model_path}')
                  sys.exit(0)
              else:
                  print('FAILED: No output model')
                  sys.exit(1)
          except Exception as e:
              print(f'FAILED: {e}')
              sys.exit(1)
          "
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-cpu-${{ matrix.name }}-output
          path: ${{ matrix.path }}/olive-output/
          retention-days: 7

  linux-gpu:
    name: Linux GPU - ${{ matrix.name }}
    if: |
      github.event.inputs.test_scope == 'all' || 
      github.event.inputs.test_scope == 'linux-gpu-only' || 
      github.event.inputs.test_scope == ''
    runs-on: [self-hosted, linux, A100]
    timeout-minutes: 180
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: "Session Param Tuning"
            path: "microsoft-resnet-50/aitk"
            config: "resnet_trtrtx.json"
          - name: "Dora"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "dora.json"
          - name: "HQQ"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "hqq.json"
          - name: "Lmeval"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "lmeval.json"
          - name: "Lmeval-ONNX"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "lmeval_onnx.json"
          - name: "Loha"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "loha.json"
          - name: "Lokr"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "lokr.json"
          - name: "QLoRA"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "qlora.json"
          - name: "RTN"
            path: "meta-llama-Llama-3.2-1B-Instruct/olive"
            config: "rtn.json"
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Olive
        run: pip install git+https://github.com/microsoft/Olive.git@main
      
      - name: Install requirements
        working-directory: ${{ matrix.path }}
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run and verify
        working-directory: ${{ matrix.path }}
        env:
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
        run: |
          python -m olive run --config ${{ matrix.config }}
          python -c "
          from olive.workflows.run import WorkflowOutput
          import sys
          try:
              output = WorkflowOutput.from_json('olive-output/output.json')
              if output.has_output_model():
                  model = output.get_best_candidate()
                  print(f'SUCCESS: Model at {model.model_path}')
                  sys.exit(0)
              else:
                  print('FAILED: No output model')
                  sys.exit(1)
          except Exception as e:
              print(f'FAILED: {e}')
              sys.exit(1)
          "
      
      - name: Cleanup GPU
        if: always()
        run: |
          nvidia-smi
          python -c "import torch; torch.cuda.empty_cache()" || true
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-gpu-${{ matrix.name }}-output
          path: ${{ matrix.path }}/olive-output/
          retention-days: 7

  windows-cpu:
    name: Windows CPU - ${{ matrix.name }}
    if: |
      github.event.inputs.test_scope == 'all' || 
      github.event.inputs.test_scope == 'windows-cpu-only' || 
      github.event.inputs.test_scope == ''
    runs-on: windows-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "PTQ"
            path: "intel-bert-base-uncased-mrpc/oci/cpu"
            config: "ptq.json"
          - name: "INC Smooth Quant"
            path: "intel-bert-base-uncased-mrpc/oci/cpu"
            config: "inc_smooth_quant.json"
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Olive
        run: pip install git+https://github.com/microsoft/Olive.git@main
      
      - name: Install requirements
        working-directory: ${{ matrix.path }}
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
      
      - name: Run and verify
        working-directory: ${{ matrix.path }}
        shell: pwsh
        env:
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
        run: |
          python -m olive run --config ${{ matrix.config }}
          python -c "from olive.workflows.run import WorkflowOutput; import sys; output = WorkflowOutput.from_json('olive-output/output.json'); sys.exit(0 if output.has_output_model() else 1)"
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-cpu-${{ matrix.name }}-output
          path: ${{ matrix.path }}/olive-output/
          retention-days: 7

