name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint:
    name: Lintrunner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-dev.txt
          lintrunner init

      - name: Run lintrunner on all files
        run: |
          if ! lintrunner --force-color --all-files --tee-json=lint.json -v; then
            echo
            echo "Run 'lintrunner --all-files' locally to reproduce these results."
            exit 1
          fi

      - name: Produce SARIF
        if: always()
        run: python -m lintrunner_adapters to-sarif lint.json lintrunner.sarif

      - name: Upload SARIF
        if: always()
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@c4dd10e44af883a891fe31ced449bcb4a6728b9b # v3.37.6
        with:
          sarif_file: lintrunner.sarif
          category: lintrunner
          checkout_path: ${{ github.workspace }}
